### ISSUE TITLE
Initial migration file shouldn't have been updated. It's already been sync'd to production DBs.

### ISSUE THREAD

**Issue by nceruchalu** [jleclanche/django-push-notifications#186] opened 2015-07-09 19:53 UTC
A commit in v1.3.1, https://github.com/jleclanche/django-push-notifications/commit/8fcc265331605241a538ebc571dac912d08f2f9f, modified the original migration file `0001_initial.py`.  This works great for new users of this well-done project as they only have 1 migration file to read through.

However this project has thankfully been around for some time and a number of us had already run a `manage.py migrate` which put this initial migration in our production DBs. **So any changes made to this migration file wouldn't have been picked up by django's migration tool.**

**It would seem more appropriate to create a new migration file by running `manage.py makemigrations` and renaming it to something like `0002_add_db_index.py`**. This way our systems don't try to create new migration for those still on versions prior to v1.3.1. 
Those who already upgraded to v1.3.1 now have a migration file that isn't in sync with their DBs and have to manually add this index to fix that.

The suggested approach is in line with Django's notes on how the migrations tool works. It can be observed that too made many new migrations in the `auth app` in the upgrade from Django v1.7 to v1.8. This way nobody's database is out of sync with the migration files, and nobody's machine is auto-generating the necessary migration files.

Please let me know your thoughts on this. And thanks for the great work on this! Has definitely served multiple people in multiple projects! :smile:

**Comment by jleclanche** [comment] 2015-07-09 19:57
If the db is correct I think you can run it as a fake migration. Unfortunately I don't actively use this project in production, so I can only rely on other people testing for me :/

**Comment by nceruchalu** [comment] 2015-07-09 20:08
Thanks for the quick response!

So the thing about fake migrations is they just ensure the `django_migrations` table in the database have an entry that say a migration file has been applied. So in this case it will say the `0001_intial.py` migration file has been applied. However this is already the case as I've had this project running in production for a while.

From the Django notes on fake migrations: **["Django won’t check that the table schema match your models, just that the right table names exist)"](https://docs.djangoproject.com/en/1.8/topics/migrations/#upgrading-from-south)**

So yes you're right that I could go update my db manually and ensure that the table schema matches by adding this index to the `push_notifications_<device>` tables. A number of your pre-existing happy users might not be too keen on doing this though when you finally publish a new pip release.

**Comment by Alp-Phone** [comment] 2015-08-23 19:28
I believe the least painful way out of this pickle is to dump, drop, recreate and restore the tables.
I agree that the changes in https://github.com/jleclanche/django-push-notifications/commit/8fcc265331605241a538ebc571dac912d08f2f9f should have been a new migration.
I don't see a way to actually fix this, do you?

**Comment by BudgieInWA** [comment] 2015-10-01 08:31
There are now people using the new migration file in production, so there is no way to fix it for everyone.

---

If I was using the old migration file, I would

1. replace the new migration file with the old migration file,
2. `manage.py makemigrations`,
3. `manage.py migrate`,
4. replace the old migration file with the new migration file and delete the auto-generated migration file,
5. edit the `django_migrations` table manually, deleting the reference to the auto-generated migration.

The result of this is that the database, migration files, and migration metadata will all match.

---

@jleclanche, read and understand at least the [workflow section](https://docs.djangoproject.com/en/1.8/topics/migrations/#workflow) of the migrations docs. It is important that you follow it so others don't run into trouble when they update. Most important:

- Never change a published migration.
- Every time a model is changed, commit the change to the model and the required migration in the same commit (or at least in the same release).

**Comment by jleclanche** [comment] 2016-08-01 17:27
Closing this as the issue is too old to do anything about now.

**Closed by jleclanche** 2016-08-01 17:27 UTC
Labels: migrations
