### ISSUE TITLE
Can't save GCMDevice with an valid UUID

### ISSUE THREAD

**Issue by YuriHeupa** [jleclanche/django-push-notifications#250] opened 2015-12-02 14:07 UTC
I'm trying to add a GCMDevice in django admin, after adding a UUID to device_id as follow:
1b9017ab-10d2-47f4-a827-a81d5d979c62

I get the following error:
`Enter a valid hexadecimal number`

So after this i did:
```
uuid.UUID("1b9017ab-10d2-47f4-a827-a81d5d979c62").hex
```

And got a value without dashes:
```
1b9017ab10d247f4a827a81d5d979c62
```

I tried again to add the device_id and i got an error saying the value need to be less or equal 9223372036854775807, so it's not possible to add a UUID to a GCMDevice?

(I'm using django-push-notifications at version 1.3.1 and django.contrib.gis.db.backends.postgis as my database engine)

## Update:
While trying to save by shell with value without dashes i got the following error:
```
File "push_notifications/fields.py", line 64, in get_prep_value
    value = struct.unpack("q", struct.pack("Q", value))[0]
error: integer out of range for 'Q' format code
```

**Comment by jamaalscarlett** [comment] 2015-12-02 14:36
Duplicate of https://github.com/jleclanche/django-push-notifications/issues/241

**Closed by jamaalscarlett** 2015-12-02 14:36 UTC

**Comment by YuriHeupa** [comment] 2015-12-02 14:41
I got the master branch, and tried to save again with the value without dashes, and now i get the same error but with different value, saying that the value need to be less or equal 18446744073709551615, so still not fixed to me
