### ISSUE TITLE
Change APNS host and cert per request

### ISSUE THREAD

**Issue by ezheidtmann** [jleclanche/django-push-notifications#261] opened 2015-12-16 23:14 UTC
I have some user iOS devices that are on the app store, and others that are development devices running a development build of our iOS app. I believe that I need change the cert and change the host depending on whether the device is a dev or non-dev device. 

Has anyone solved this problem before? If not, I will strike out on my own and contribute what I do.

-Evan

**Comment by whiskey** [comment] 2015-12-21 11:03
A quick tip is to save a 'tag' upon token registration like 'dev'/'prod'. Parse is using similar concepts with their channels.

**Comment by ezheidtmann** [comment] 2015-12-21 17:25
@whiskey Thanks! I don't think that addresses my question, though. I have one Django instance that needs to send APNS messages two different iOS apps (i.e. two different certs). But maybe I don't understand what you're saying?

**Comment by jleclanche** [comment] 2016-01-04 20:50
Dupe of #130

**Closed by jleclanche** 2016-01-04 20:50 UTC
