### ISSUE TITLE
Send test message not working

### ISSUE THREAD

**Issue by tyapkov** [jleclanche/django-push-notifications#391] opened 2017-04-26 09:59 UTC
I am trying to setup django-push-notifications and added just one device to db.

When trying to send_message from admin I get:

```
Django Version: 	1.11
Exception Type: 	TypeError
Exception Value: 	

sequence item 0: expected str instance, dict found

Exception Location: 	/usr/local/lib/python3.5/dist-packages/push_notifications/admin.py in send_messages, line 54
Python Executable: 	/usr/bin/python3
Python Version: 	3.5.2

 /usr/local/lib/python3.5/dist-packages/push_notifications/admin.py in send_message

    		self.send_messages(request, queryset)

/usr/local/lib/python3.5/dist-packages/push_notifications/admin.py in send_messages

    				ret = ", ".join(ret)
```

**Comment by aleksihakli** [comment] 2017-04-28 08:55
I can reproduce this. Seems like `send_test_message` actually *works* for us but the admin panel message rendering is broken. On [line 54 in admin.py](https://github.com/jleclanche/django-push-notifications/blob/master/push_notifications/admin.py#L54) `ret = ', '.join(ret)` seems to be getting a list of one dictionary as input type and crashes with that join.

I guess one option would be to cast that list into a string or otherwise handle the message rendering in admin panel in a more error-tolerant way?

**Comment by alexche8** [comment] 2017-07-26 12:59
Any changes on this? Can't send push notifications from admin page while use android, but ios is ok.

**Comment by jamaalscarlett** [comment] 2017-08-16 11:20
@tyapkov @aleksihakli Can you verify that is is fixed in the master branch?

**Comment by jamaalscarlett** [comment] 2017-08-23 03:27
@alexche8 can you test this against the master branch?

**Closed** 2017-08-23 16:31 UTC

**Comment by aleksihakli** [comment] 2017-09-05 13:40
Sorry for the late reply @jamaalscarlett. I'd need a new release to verify this on our project but the fix code seems good to me :) Thanks for the fix!
