### ISSUE TITLE
Cant save GCMDevice

### ISSUE THREAD

**Issue by tsouvarev** [jleclanche/django-push-notifications#190] opened 2015-07-23 12:20 UTC
I have GCMDevice, which stores in PostgreSQL, with some hex device_id. When I load this object from db, following code runs in [to_python](https://github.com/jleclanche/django-push-notifications/blob/master/push_notifications/fields.py#L74): `hex(struct.unpack("Q", struct.pack("q", value))[0])` which results in hex like `0xc4ffbd6714000b33L`. After some changes I try to save device and in [get_prep_value](https://github.com/jleclanche/django-push-notifications/blob/master/push_notifications/fields.py#L61) code `value = int(value, 16)` fails with `ValueError: invalid literal for int() with base 16: '0xc4ffbd6714000b33L'`
Problem is `hex` function which produces hex code with L (and this is bad for `int` function later)
Possible solution: use `0x%x % long_integer` to get hex code

**Comment by jamaalscarlett** [comment] 2015-07-23 13:27
Are you running the latest version 1.3.1?

**Comment by tsouvarev** [comment] 2015-07-23 13:56
@jamaalscarlett I was running v1.2.0, but for v1.3.1 bug still actual

**Comment by jamaalscarlett** [comment] 2015-07-24 18:19
This is from fieilds.py:
	This field stores a hexadecimal *string* of up to 64 bits as an unsigned integer
	on *all* backends including postgres.

	Reasoning: Postgres only supports signed bigints. Since we don't care about
	signedness, we store it as signed, and cast it to unsigned when we deal with
	the actual value (with struct)

	On sqlite and mysql, native unsigned bigint types are used. In all cases, the
	value we deal with in python is always in hex.

So on all other backends, signed values are not allowed.  I verified this with mysql, when you update the column with a negative number, it is saved as 0.  The column is only signed in psql because postgres only has signed bigints.  The correct approach would to be only allow unsigned integers which is how the field currently functions.

**Comment by tsouvarev** [comment] 2015-07-24 18:44
So you saying, that's the feature but not bug, that I can't change created device? :)

**Comment by jamaalscarlett** [comment] 2015-07-24 19:19
I didn't write the code, but from the comment it appears that the device_id should never be a negative number.  I can reproduce the issue, but I don't think it is a bug.  You can change the device id, you just cannot set it to a negative number.

**Comment by tsouvarev** [comment] 2015-07-30 07:10
actually, from this:
```text
Reasoning: Postgres only supports signed bigints. Since we don't care about
signedness, we store it as signed, and cast it to unsigned when we deal with
the actual value (with struct)
```
follows that we don't care about storage, we just read it in Python always as unsigned (struct's `Q` is for `unsigned long long`)

**Comment by jamaalscarlett** [comment] 2015-07-31 13:40
The comment is misleading because 'signedness' is important.  As I stated before, if you attempted to save that negative number with a backend configured to mysql, it would save as 0.  The code should function the same, regardless of the backend you choose.  The real fix is to validate that the number is positive before inserting it into the database.

**Comment by jleclanche** [comment] 2015-07-31 13:48
> if you attempted to save that negative number with a backend configured to mysql, it would save as 0

On mysql, we specifically ask for an unsigned bigint, so the number will never be negative

**Comment by jamaalscarlett** [comment] 2015-12-01 15:13
@tsouvarev can you try the latest from the master branch, it should fix your issue

**Comment by tsouvarev** [comment] 2015-12-02 07:51
Yep, it works now

**Comment by jamaalscarlett** [comment] 2015-12-02 12:17
Fixed by 01f65a23e326bf9c24c6e1be0e61b8efbf7aeaac

**Closed by jamaalscarlett** 2015-12-02 12:17 UTC

**Comment by YuriHeupa** [comment] 2015-12-02 13:42
Is this published on pypi?

**Comment by jamaalscarlett** [comment] 2015-12-02 14:35
Not yet.
