### ISSUE TITLE
Using several certificates instead of one

### ISSUE THREAD

**Issue by Closius** [jleclanche/django-push-notifications#286] opened 2016-03-13 12:08 UTC
When I develop my app it could be useful if my app is able to send push notification using developer and production certificates together (e.g. sequential sending).

Can I do it via django-push-notification?

**Comment by Vektrat** [comment] 2016-03-18 11:52
I think apple has recently changed it so that you can have just one certificate for production and sandbox if using HTTP2. Otherwise I suggest that you have different setting files for your environments and that the common variable for the certificate differs in the path, or that you create an environment variable that has a different certificate in each environment.

**Comment by jleclanche** [comment] 2016-07-22 03:00
Dupe of #130

**Closed by jleclanche** 2016-07-22 03:00 UTC
