### ISSUE TITLE
GCMError when sending bulk message

### ISSUE THREAD

**Issue by akonya** [jleclanche/django-push-notifications#145] opened 2015-04-28 15:20 UTC
The code which was run to throw the error
```python
extraGCM = {"type":"message","convoId":self.id,"message":msg,"title":"app_name"}
anl = list(map((lambda x: x.participant.name),pl2))
#get devices from list of names
googleDevices = GCMDevice.objects.filter(name__in = anl)
if googleDevices.exists():
    googleDevices.send_message(None,extra=extraGCM)
```

Returned error:
```javascript
GCMError: {u'failure': 5, u'canonical_ids': 0, u'success': 0, u'multicast_id': 7823303804817593297, u'results':
 [
{u'error': u'NotRegistered'}, {u'error': u'NotRegistered'}, {u'error': u'NotRegistered'}, {u'error': u'NotRegistered'}, {u'error': u'NotRegistered'}
]}
```

From what I understand these are devices which have uninstalled the app, or are no longer registered for push for some reason.  I think I just need to delete the devices which return the not registered errors, but I do not see a way to do that.

**Comment by pcompassion** [comment] 2015-04-30 13:48
I asked the same question few days ago.
It's not implemented yet. 

https://github.com/jleclanche/django-push-notifications/issues/142

**Comment by nicusorbinovate** [comment] 2015-06-04 07:05
any ideea when it will be fixed?

**Comment by jleclanche** [comment] 2015-06-04 07:27
Sorry I have no way to test this. If someone is able to fix it, feel free to PR.

**Comment by jamaalscarlett** [comment] 2015-06-08 04:13
I've got a fix I'm working on.  I've currently have it set active=0 in the model when the NotRegistered error is returned.  I still need to add support for these possible errors:https://developers.google.com/cloud-messaging/server-ref#table11 as well.

**Comment by jamaalscarlett** [comment] 2015-06-09 18:19
PR is in: https://github.com/jleclanche/django-push-notifications/pull/158

**Comment by jleclanche** [comment] 2015-06-30 09:00
Dupe of #44 which is fixed

**Closed by jleclanche** 2015-06-30 09:00 UTC
